app.py
from flask import Flask

from source.configuration import secret_key
from source.routes import blog_app


def create_app() -> Flask:
    """ Flask app factory. """
    
    app = Flask(__name__)
    app.secret_key = secret_key
    app.register_blueprint(blog_app, url_prefix='/')
    
    return app

source/routes.py
from flask import Blueprint
from pymongo import MongoClient

from source.configuration import db_uri
from source.db import MongoDBCrud, get_db_crud_entries, get_db_crud_users
from source.routing import Router

db_client: MongoClient = MongoClient(db_uri)
router = Router(
    get_db_crud_users(MongoDBCrud, db_client),
    get_db_crud_entries(MongoDBCrud, db_client))

blog_app = Blueprint('blog_app', __name__)


@blog_app.route("/", methods=['GET', 'POST'])
def home():
    return router.home()


@blog_app.route('/login', methods=['GET', 'POST'])
def login():
    return router.login()


@blog_app.route('/logout', methods=['GET', 'POST'])
def logout():
    return router.logout()


@blog_app.route('/signup', methods=['GET', 'POST'])
def signup():
    return router.signup()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Techie blog</title>
    <link rel="stylesheet" href="/static/css/styles.css">
</head>
<body>
    <header class="navbar">
        <div class="navbar__brand">
            <img class="navbar__logo" src="/static/icon.png" alt="Micro-blog logo">Techie_blog
        </div>
        <ul class="navbar__navigation">
            <li class="navbar__navigation-item">
                <a href="/" class="navbar__link">Posts</a>
            </li>
            <li class="navbar__navigation-item">
                {% if not user  %}
                    <a href="/login" class="navbar__link">Log in</a>
                {% else %}
                    <a href="/logout" class="navbar__link">{{ user }}</a>
                {% endif %}
            </li>
        </ul>
    </header>
    
    <main class="main">
        <div class="flashed_window">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="footer__content">
            <section class="left">
                <a class="footer__item">Made by David Kovacs</a>
                <a class="footer__item" href="https://github.com/PyKovacs">Check out my other projects on Github</a>
            </section>
            <section class="right">
                <div class="footer__column">
                    <a class="footer__item" href="/">Posts</a>
                    <a class="footer__item" href="/calendar">Calendar</a>
                </div>
                <div class="footer__column">
                    <a class="footer__item">About</a>
                    <a class="footer__item">How this was made</a>
                </div>
            </section>
        </div>
    </footer>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Techie blog</title>
    <link rel="stylesheet" href="/static/css/styles.css">
</head>
<body>
    <header class="navbar">
        <div class="navbar__brand">
            <img class="navbar__logo" src="/static/icon.png" alt="Micro-blog logo">Techie_blog
        </div>
        <ul class="navbar__navigation">
            <li class="navbar__navigation-item">
                <a href="/" class="navbar__link">Posts</a>
            </li>
            <li class="navbar__navigation-item">
                <a href="/calendar" class="navbar__link">Calendar</a>
            </li>
        </ul>
    </header>
    <main class="main">
        {% if main == 'posts' %}
            <section>
                <h1>Add new entry</h1>
                <form class="form" method="POST">
                    <p class="form__input">
                        <label class="form__label" for="entry">Entry content:</label>
                        <textarea class="form__textarea" name="content" id="entry"></textarea>
                    </p>
                    <button class="form__submit" type="submit">Add entry</button>
                </form>
            </section>
            <section>
                <h1>Recent posts</h1>
                {% for entry in entries %}
                    <article class="entry">
                        <div>
                            <h2 class="entry__title">{{ entry[0] | truncate(30, true) }}</h2>
                            <time class="entry__date" datetime="{{ entry[1] }}"> | {{ entry[2] }}</time>
                        </div>
                        <p class="entry__content">
                            {{ entry[0] }}
                        </p>
                    </article>
                {% endfor %}
            </section>
        {% elif main == 'calendar' %}
            <h2>Work in progress...</h2>
        {% endif %}
    </main>
    <footer class="footer">
        <div class="footer__content">
            <section class="left">
                <a class="footer__item">Made by David Kovacs</a>
                <a class="footer__item" href="https://github.com/PyKovacs">Check out my other projects on Github</a>
            </section>
            <section class="right">
                <div class="footer__column">
                    <a class="footer__item" href="/">Posts</a>
                    <a class="footer__item" href="/calendar">Calendar</a>
                </div>
                <div class="footer__column">
                    <a class="footer__item">About</a>
                    <a class="footer__item">How this was made</a>
                </div>
            </section>
        </div>
    </footer>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" class="login-form">
    <input class="login-form__input" type="text" name="username" placeholder="Username">
    <input class="login-form__input" type="password" name="password" placeholder="Password">
    <button class="login-form__submit" type="submit">Log in</button>
</form>
<p>
    New here?
    <a href="{{ url_for('blog_app.signup') }}"> Sign up</a> instead!
</p>
{% endblock %}
 

templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="login-form">
        <button class="login-form__submit" type="submit">Log out</button>
    </form>
{% endblock %}
 

templates/posts.html
{% extends 'base.html' %}

{% block content %}
    <p style=
        "color: gray;
        margin-bottom: 70px;
        {{ 'display: none;' if user }}">
        <em>Log in to submit new posts.</em>
    </p>
    <section style="{{ 'display: none;' if not user }}">
        <h1>Add new entry</h1>
        <form class="form" method="POST">
            <p class="form__input">
                <label class="form__label" for="entry">Entry content:</label>
                <textarea class="form__textarea" name="content" id="entry"></textarea>
            </p>
            <button class="form__submit" type="submit">Add entry</button>
        </form>
    </section>
    <section>
        <h1>All posts</h1>
        {% for entry in entries %}
            <article class="entry">
                <div>
                    <p class="entry__user">{{ entry[1] }}</p>
                    <h2 class="entry__title">{{ entry[0] | truncate(30, true) }}</h2>
                    <time class="entry__date" datetime="{{ entry[2] }}"> | {{ entry[3] }}</time>
                </div>
                <p class="entry__content">
                    {{ entry[0] }}
                </p>
            </article>
        {% endfor %}
    </section>
{% endblock %}
 

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" class="login-form">
    <input class="login-form__input" type="text" name="username" placeholder="Username">
    <input class="login-form__input" type="password" name="password" placeholder="Password">
    <button class="login-form__submit" type="submit">Sign up</button>
</form>
<p>
<a href="{{ url_for('blog_app.login') }}"> Log in</a> instead.
</p>
{% endblock %}
 